
trigger:
  branches:
    include:
      - main

resources:
  repositories:
    # You do not have to checkout this repo to use the templates
    - repository: utils
      type: github
      name: 'launchbynttdata/lcaf-component-provider_az-pipeline_azdo'
      ref: feature/1456
      endpoint: 'launchbynttdata-github-token'

variables:
  # This is how you set variables for the repositories
  utils_name: $[ resources.repositories.utils.name ]
  # Variables for service connection. You cannot dynamically set them in tasks
  service_connection_uat: "ado-sp"
  service_connection_test: "ado-sp"
  service_connection_prod: "ado-sp"
  service_connection_dev: "ado-sp"

parameters:
  # serviceConnection may be different for each environment in real-world scenarios
  - name: serviceConnection
    type: string
    default: 'ado-sp'
  - name: agentPool
    type: string
    default: 'container-pool'
  - name: acrName
    type: string
    default: 'dsopublic.azurecr.io'
  - name: dockerImageName
    type: string
    default: 'sample-dotnetcore-app'
  # If imageTag is set to "None", the build ID will be used as the image tag
  - name: imageTag
    type: string
    default: "None"
  
stages:
  - stage: BuildAndPush
    displayName: 'Build and Push Docker Image'
    jobs:
      - job: BuildAndPushJob
        displayName: 'Build and Push'
        pool: ${{ parameters.agentPool }}
        steps:
          - template: /iac/steps/verify-ado-agent.yaml@utils
          - template: /iac/steps/acr-build-push-docker-image.yaml@utils
            parameters:
              serviceConnection: ${{ parameters.serviceConnection }}
              dockerImageName: ${{ parameters.dockerImageName }}
              dockerImageTag: $(Build.BuildId)
              acrRegistry: ${{ parameters.acrName }}

  - template: /iac/stages/helm-app-deploy.yaml@utils
    parameters:
      agentPool: ${{ parameters.agentPool }}
      deployEnvironments:
        - environment: 'dev'
          dependsOn: 'BuildAndPush'
          variableFile: '/envs/dev/pipelines/variables.yaml@self'
          acrName: ${{ parameters.acrName }}
          imageName: ${{ parameters.dockerImageName }}
          imageTag: ${{ parameters.imageTag }}
        - environment: 'test'
          dependsOn: 'dev_Deploy'
          variableFile: '/envs/test/pipelines/variables.yaml@self'
          acrName: ${{ parameters.acrName }}
          imageName: ${{ parameters.dockerImageName }}
          imageTag: ${{ parameters.imageTag }}
        - environment: 'uat'
          dependsOn: 'test_Deploy'
          variableFile: '/envs/uat/pipelines/variables.yaml@self'
          acrName: ${{ parameters.acrName }}
          imageName: ${{ parameters.dockerImageName }}
          imageTag: ${{ parameters.imageTag }}
        - environment: 'prod'
          dependsOn: 'uat_Deploy'
          variableFile: '/envs/prod/pipelines/variables.yaml@self'
          acrName: ${{ parameters.acrName }}
          imageName: ${{ parameters.dockerImageName }}
          imageTag: ${{ parameters.imageTag }}
  